export const GET_ERRORS = 'GET_ERRORS';
export const LANGUAGE_LOADING='LANGUAGE_LOADING';
export const GET_LANGUAGES='GET_LANGUAGES';
export const GET_LANGUAGE='GET_LANGUAGE';
export const CLEAR_ERRORS='CLEAR_ERRORS';
